services:
  dev:
    profiles: ["dev"]
    build:
      context: .
      target: dev
    ports:
      - "8050:8050"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env

  prod:
    profiles: ["prod"]
    build:
      context: .
      target: runner
    ports:
      - "8050:8050"
    env_file:
      - .env
    restart: unless-stopped
