-- Many-to-one link between Telegram accounts and access codes. One row per
-- (access_code, telegram_id) pair; an access code can have many Telegram
-- accounts linked to it.
--
-- Sessions themselves stay in the browser's localStorage (the session
-- string grants full Telegram access — keeping it client-side avoids
-- storing that secret on the server). This table tracks WHICH Telegram
-- accounts each access code has been used with — useful for admin
-- visibility and future per-access-code account restoration.
create table if not exists public.telegram_accounts (
  id           bigint generated by default as identity primary key,
  access_code  text not null,
  telegram_id  text not null,
  phone        text,
  first_name   text,
  last_name    text,
  username     text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint telegram_accounts_access_code_fk
    foreign key (access_code) references public.access_codes(code) on delete cascade,
  constraint telegram_accounts_access_code_telegram_id_uniq
    unique (access_code, telegram_id)
);

create index if not exists telegram_accounts_access_code_idx
  on public.telegram_accounts (access_code);
create index if not exists telegram_accounts_telegram_id_idx
  on public.telegram_accounts (telegram_id);
