import { createClient } from "@/lib/telegram";
import { Api, utils as telegramUtils } from "telegram";
import bigInt from "big-integer";
import { resolveUserPeer } from "@/lib/telegram-peer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Media attached to a chat message, classified for the UI to render. */
export type ChatMedia = {
  kind:
    | "photo"
    | "video"
    | "sticker"
    | "gif"
    | "voice"
    | "audio"
    | "file"
    | "contact";
  /** Inline low-res preview (base64 JPEG data URL) — shows instantly. */
  thumb?: string;
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
  /** Seconds, for video / voice / audio. */
  duration?: number;
  width?: number;
  height?: number;
  /** Shared-contact fields (kind === "contact"). */
  contactUserId?: string;
  contactFirstName?: string;
  contactLastName?: string;
  contactPhone?: string;
};

/** Telegram webpage/link preview metadata attached to a text message. */
export type LinkPreview = {
  url: string;
  displayUrl?: string;
  siteName?: string;
  title?: string;
  description?: string;
  /** True when Telegram attached a webpage image that can be streamed. */
  hasImage?: boolean;
  /** Inline low-res webpage image preview, when Telegram provides one. */
  thumb?: string;
};

/** Where a forwarded message originated — name plus the peer for its photo. */
export type ForwardInfo = {
  /** Display name of the origin chat or user. */
  name: string;
  /** Origin peer id — used to fetch its profile photo. */
  id?: string;
  /** Origin peer access hash — lets the photo resolve on a cold client. */
  accessHash?: string;
  /** True when the origin is a channel/supergroup. */
  isChannel?: boolean;
  /** True when the origin is a user (vs a channel/group). */
  isUser?: boolean;
  /** Public @username of the origin, when it has one — enables click-to-open. */
  username?: string;
};

export type ChatMessage = {
  id: number;
  text: string;
  date: number;
  fromMe: boolean;
  status?: "sent" | "read";
  media?: ChatMedia;
  /** Shared id for messages sent together as one album (grouped media). */
  groupedId?: string;
  /** Sender id — set for group/channel messages so the UI can label them. */
  senderId?: string;
  /** Sender display name — set for group/channel messages. */
  senderName?: string;
  /** Origin info when this message is a forward. */
  forwardedFrom?: ForwardInfo;
  /** Link preview generated by Telegram for webpage/deep links. */
  linkPreview?: LinkPreview;
};

/** Decode a Telegram stripped thumbnail into an inline JPEG data URL. */
function strippedToDataUrl(
  stripped: Api.PhotoStrippedSize,
): string | undefined {
  try {
    const jpg = telegramUtils.strippedPhotoToJpg(Buffer.from(stripped.bytes));
    return `data:image/jpeg;base64,${Buffer.from(jpg).toString("base64")}`;
  } catch {
    return undefined;
  }
}

function photoThumb(photo: Api.TypePhoto): string | undefined {
  if (!(photo instanceof Api.Photo)) return undefined;
  for (const s of photo.sizes) {
    if (s instanceof Api.PhotoStrippedSize) return strippedToDataUrl(s);
  }
  return undefined;
}

function extractLinkPreview(media: Api.TypeMessageMedia): LinkPreview | null {
  if (!(media instanceof Api.MessageMediaWebPage)) return null;
  const page = media.webpage;
  if (!(page instanceof Api.WebPage)) return null;

  const url = page.url || page.displayUrl;
  if (!url) return null;

  return {
    url,
    displayUrl: page.displayUrl || undefined,
    siteName: page.siteName || undefined,
    title: page.title || undefined,
    description: page.description || undefined,
    hasImage: page.photo instanceof Api.Photo,
    thumb: page.photo ? photoThumb(page.photo) : undefined,
  };
}

/** Classify a message's media into a UI-friendly shape. */
function classifyMedia(media: Api.TypeMessageMedia): ChatMedia | null {
  if (media instanceof Api.MessageMediaContact) {
    return {
      kind: "contact",
      contactUserId: media.userId ? media.userId.toString() : undefined,
      contactFirstName: media.firstName || "",
      contactLastName: media.lastName || "",
      contactPhone: media.phoneNumber || "",
    };
  }

  if (media instanceof Api.MessageMediaPhoto) {
    const photo = media.photo;
    let thumb: string | undefined;
    let width: number | undefined;
    let height: number | undefined;
    if (photo instanceof Api.Photo) {
      for (const s of photo.sizes) {
        if (s instanceof Api.PhotoStrippedSize) {
          thumb = strippedToDataUrl(s);
        } else if (
          s instanceof Api.PhotoSize ||
          s instanceof Api.PhotoSizeProgressive
        ) {
          width = s.w;
          height = s.h;
        }
      }
    }
    return { kind: "photo", thumb, width, height };
  }

  if (media instanceof Api.MessageMediaDocument) {
    const doc = media.document;
    if (!(doc instanceof Api.Document)) return null;

    let fileName: string | undefined;
    let duration: number | undefined;
    let width: number | undefined;
    let height: number | undefined;
    let isVideo = false;
    let isVoice = false;
    let isSticker = false;
    let isAnimated = false;

    for (const attr of doc.attributes) {
      if (attr instanceof Api.DocumentAttributeFilename) {
        fileName = attr.fileName;
      } else if (attr instanceof Api.DocumentAttributeVideo) {
        isVideo = true;
        duration = attr.duration;
        width = attr.w;
        height = attr.h;
      } else if (attr instanceof Api.DocumentAttributeAudio) {
        duration = attr.duration;
        if (attr.voice) isVoice = true;
      } else if (attr instanceof Api.DocumentAttributeSticker) {
        isSticker = true;
      } else if (attr instanceof Api.DocumentAttributeAnimated) {
        isAnimated = true;
      } else if (attr instanceof Api.DocumentAttributeImageSize) {
        width = attr.w;
        height = attr.h;
      }
    }

    let kind: ChatMedia["kind"];
    if (isSticker) kind = "sticker";
    else if (isAnimated) kind = "gif";
    else if (isVideo) kind = "video";
    else if (isVoice) kind = "voice";
    else if ((doc.mimeType || "").startsWith("audio/")) kind = "audio";
    else kind = "file";

    let thumb: string | undefined;
    for (const t of doc.thumbs ?? []) {
      if (t instanceof Api.PhotoStrippedSize) thumb = strippedToDataUrl(t);
    }

    return {
      kind,
      thumb,
      fileName,
      fileSize: Number(doc.size),
      mimeType: doc.mimeType,
      duration,
      width,
      height,
    };
  }

  return null;
}

/** Extract the sender id + display name from a group/channel message. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function extractSender(msg: any): { id?: string; name?: string } {
  const from = msg.fromId;
  let id: string | undefined;
  if (from instanceof Api.PeerUser) id = from.userId.toString();
  else if (from instanceof Api.PeerChannel) id = from.channelId.toString();
  else if (from instanceof Api.PeerChat) id = from.chatId.toString();
  // GramJS attaches the resolved entity as `_sender` after getMessages.
  const sender = msg._sender;
  let name = "";
  if (sender) {
    if (sender.firstName || sender.lastName) {
      name = `${sender.firstName || ""} ${sender.lastName || ""}`.trim();
    } else if (sender.title) {
      name = sender.title;
    }
  }
  return { id, name: name || undefined };
}

/**
 * Where a forwarded message came from — name + origin peer — or undefined for
 * normal messages (including content re-uploaded from a restricted chat,
 * which carries no forward header).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function extractForward(msg: any): ForwardInfo | undefined {
  const fwd = msg.fwdFrom;
  if (!fwd) return undefined;

  let name: string | undefined;
  // Hidden original sender — Telegram sends a bare name string.
  if (typeof fwd.fromName === "string" && fwd.fromName.trim()) {
    name = fwd.fromName.trim();
  }

  let id: string | undefined;
  let accessHash: string | undefined;
  let username: string | undefined;
  let isChannel = false;
  let isUser = false;
  try {
    // GramJS' Forward helper carries the resolved origin entity.
    const origin = msg.forward?.chat ?? msg.forward?.sender;
    if (origin) {
      id = origin.id?.toString();
      if (typeof origin.username === "string" && origin.username) {
        username = origin.username;
      }
      if (origin instanceof Api.Channel) {
        isChannel = true;
        accessHash = origin.accessHash?.toString();
      } else if (origin instanceof Api.User) {
        isUser = true;
        accessHash = origin.accessHash?.toString();
      }
      if (!name) {
        name =
          origin.title ||
          `${origin.firstName || ""} ${origin.lastName || ""}`.trim() ||
          undefined;
      }
    }
  } catch {
    // ignore — fall through to the post-author signature
  }

  if (!name && typeof fwd.postAuthor === "string" && fwd.postAuthor.trim()) {
    name = fwd.postAuthor.trim();
  }

  if (!name) return undefined;
  return { name, id, accessHash, isChannel, isUser, username };
}

/** Map a GramJS message to the client-facing shape. */
function mapMessage(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  msg: any,
  readOutboxMaxId: number,
  isGroup: boolean,
): ChatMessage | null {
  if (!(msg instanceof Api.Message)) return null;
  const text: string = msg.message || "";
  const fromMe = Boolean(msg.out);
  const media = msg.media ? classifyMedia(msg.media) : null;
  const linkPreview = msg.media ? extractLinkPreview(msg.media) : null;
  // Sender labelling is only relevant for group/channel streams.
  const sender = isGroup && !fromMe ? extractSender(msg) : {};
  return {
    id: msg.id,
    text,
    date: msg.date,
    fromMe,
    // Outgoing messages the peer has already read are "seen" — Telegram tracks
    // this per-dialog via readOutboxMaxId, not per-message.
    status: fromMe ? (msg.id <= readOutboxMaxId ? "read" : "sent") : undefined,
    media: media ?? undefined,
    groupedId: msg.groupedId ? msg.groupedId.toString() : undefined,
    senderId: sender.id,
    senderName: sender.name,
    forwardedFrom: extractForward(msg),
    linkPreview: linkPreview ?? undefined,
  };
}

export async function POST(request: Request) {
  const { sessionString, userId, accessHash, chatId, limit, offsetId, initial } =
    await request.json();
  if (typeof sessionString !== "string" || !sessionString) {
    return Response.json({ error: "Missing sessionString" }, { status: 400 });
  }
  // Either a 1-to-1 user chat (userId) or a group/channel stream (chatId).
  const isGroup = !!chatId;
  if (!userId && !chatId) {
    return Response.json({ error: "Missing chat target" }, { status: 400 });
  }

  const client = createClient(sessionString);
  try {
    await client.connect();

    // Resolve the peer:
    //  - user → an explicit InputPeerUser so it works on a cold client;
    //  - channel with an access hash (e.g. a forward origin not in the
    //    account's dialogs) → an explicit InputPeerChannel;
    //  - any other group/channel → the marked id, which resolves directly.
    let peer: string | Api.InputPeerUser | Api.InputPeerChannel;
    if (!isGroup) {
      peer = await resolveUserPeer(client, userId, accessHash);
    } else if (accessHash) {
      const [bareId] = telegramUtils.resolveId(bigInt(String(chatId)));
      peer = new Api.InputPeerChannel({
        channelId: bareId,
        accessHash: bigInt(String(accessHash)),
      });
    } else {
      peer = String(chatId);
    }

    // Read state — the highest outgoing message id the peer has read. Used to
    // mark our own messages as "seen". Best-effort; user chats only.
    let readOutboxMaxId = 0;
    if (!isGroup && peer instanceof Api.InputPeerUser) {
      try {
        const res = await client.invoke(
          new Api.messages.GetPeerDialogs({
            peers: [new Api.InputDialogPeer({ peer })],
          }),
        );
        const dialog = res.dialogs?.[0];
        if (dialog instanceof Api.Dialog) {
          readOutboxMaxId = dialog.readOutboxMaxId ?? 0;
        }
      } catch {
        // ignore — messages still load, just without seen ticks
      }
    }

    const pageSize = Math.min(200, Math.max(1, Number(limit) || 50));
    // offsetId paginates into older history — getMessages returns messages
    // with id < offsetId. Omitted/0 ⇒ newest messages.
    const getOpts: { limit: number; offsetId?: number } = { limit: pageSize };
    const parsedOffset = Number(offsetId);
    if (Number.isFinite(parsedOffset) && parsedOffset > 0) {
      getOpts.offsetId = parsedOffset;
    }
    const messages = await client.getMessages(peer, getOpts);

    // getMessages returns newest-first; reverse for chronological display.
    const mapped: ChatMessage[] = [];
    for (let i = messages.length - 1; i >= 0; i--) {
      const m = mapMessage(messages[i], readOutboxMaxId, isGroup);
      if (m) mapped.push(m);
    }

    // On the first load of a channel reached by access hash (a forward
    // origin), report whether the account is already a member so the chat can
    // hide its Join button. `left` is set when the account isn't a member.
    let isMember: boolean | undefined;
    if (initial && isGroup && accessHash) {
      try {
        const entity = await client.getEntity(peer);
        if (
          entity instanceof Api.Channel ||
          entity instanceof Api.Chat
        ) {
          isMember = !entity.left;
        }
      } catch {
        // ignore — leave membership unknown
      }
    }

    return Response.json({ messages: mapped, isMember });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Failed to load conversation";
    return Response.json({ error: message }, { status: 500 });
  } finally {
    try {
      await client.disconnect();
    } catch {
      // ignore
    }
  }
}
